[theme]
primaryColor="#4B56D2"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
enableStaticServing = false

[browser]
gatherUsageStats = false