[firebase]
api_key = "AIzaSyDt4_Wzpnhow9ckDjoojQHy-OvbMcSKXg0"
auth_domain = "wallet-3f13a.firebaseapp.com"
project_id = "wallet-3f13a"
storage_bucket = "wallet-3f13a.appspot.com"
messaging_sender_id = "715972524478"
app_id = "1:715972524478:web:2b446b7e8134ac6adce1ef"
database_url = ""