[firebase]
api_key="AIzaSyD-xk2E2ufLCX6YP2cjhw8msvnT8mFk11o"
auth_domain="wallet-backup-b3078.firebaseapp.com"
project_id="wallet-backup-b3078"
storage_bucket="wallet-backup-b3078.firebasestorage.app"
messaging_sender_id="698414335396"
app_id="1:698414335396:web:b27357319b422759b0ed31"
database_url=""
measurementId="G-3F21N8Y6TZ"


[firebase_service_account]
type="service_account"
project_id="wallet-backup-b3078"  
private_key_id="ced5627cf17127a57fb3f627a9d382abc14aebfc"
client_email="firebase-adminsdk-fbsvc@wallet-backup-b3078.iam.gserviceaccount.com"
client_id="107323320010135862698"
auth_uri="https://accounts.google.com/o/oauth2/auth"
token_uri="https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40wallet-3f13a.iam.gserviceaccount.com"
universe_domain="googleapis.com"
private_key="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQClNnHd89m0fBhA\nzP/SGPAjXlLZcF+CGzZDiMA9CtG6iv1cdRYxWpDsZ4Sdy71ZaEFILHm7F9GjOWZZ\n3kDN3z/Wkb/HWbh74LPWpQFtXN57i+NXJevLRPyd1O3K7FjznF4goQaexbrwvEjU\n8zIQgdZoF1moACk/rYeWDTeEqpkxm9fRNkTPct/FCYRbkDEBr2KWb6W4NSwjYjJ6\nsohWMjBd4XEiJcWwhzhViD8iGRAnj0JXDPpZ7xkOxQZ71I9b9pArKYJMC779gI65\n89T7IVs5nfFz0s0DxS0tsvKHVkBqNXx/L69y9aOtdxb4BwrlDgXi0++7pGi4IdSI\nBQgj3wjvAgMBAAECggEAKdgzWOsFTfBMWEVT2gvU7rBaPZZ3qkVoJgzB2/QckKnZ\naAyD1XZB1I6XiTvsNnPwbO5O2rM6tqO4J7TiJwKPcbIyp7QyxLVx90CNrvxhoVsZ\n9p21LiPH89XVcJsSIImPUaZXPemI4qZdsAn0uTeZbX3UiHeZ+vXhrICmeiSXbnfJ\nGQsl2Bju84LtJuwghj2OllkusTtynWh5JVAucJLB5NBuhXkaz6KWJmB1REUTqxxL\nVhhDKPw6kreJ23QNnqCDruEbHVwOGRVeiqpCxxVk6V2F/m6am933t2DAy2diyL0P\nLhBd0pu4XlKeir2dF4w52rbnY8Lqatb74ltrWPEOkQKBgQDWoBhfsEEV3qTuCqzm\nRcdjXSbpZPxfmsoZIt1VHKCA9eqs6keJxyfQ9wqArcxFrmbb/DHx5Kp2KWH4F2Bc\nys5ATBk+Y/Azh15wocBWaVQ1lB9taz5ZEwSe6duhWPboC8BqVg9OEziX8y8Oq5We\nGGhJhu8XXbT8q4dUP1lh671MFwKBgQDFD8zV4Wo4IkvWzN2vxv5sklKLNoyPwVkW\nzTmHLIivxHa5Bdu7LtxgZg3nlzIwFwoqI5ZOUZbwLfq+hM/aXrkz4346hcU3oyzv\nQWnWPeZRHHEvYSSLtwBB7uLVzDxNVwK2qAfgJfT750TzMeX57eTG+HvE8Im1CGcC\nXk3CzqZ46QKBgQCJsFNyr+RRX3B3timN4R41RMF94ed2fhtBXPiZbbAai6luHS6f\n2UBV8uat/tGZsnUSlAyGnqgs/gd33adYYFNJNIjNWdfzdtjDcUGvLgt0A/7Vd4Oc\nKXNBb84TCLv9yew7S9Ktx+76rGx4AOQPdKES6pngZ6GAp5o+FhYFl/LtKQKBgHle\nnd4tE2q3VNZbHz6f5Ruhk01Cr5fqkaBFjeT/PMBk1GpofUjwN7L3qCC3MqYDyrLh\ncDWUcs5Cw2iMDCiGprKarqgEs87spURGmZTmUvAqAFwaDJQwhewV4YekXo+Tw4wU\nOaWIOzba3dCbLvWb24fgivpk26uwHSGMS4BsHoPhAoGBALDar/S7F3tuFZT9D7sE\nNGIcxYpjDye7Yvjx9DBSSpOW35sI8pT546lwQdndwKDfGPG7sbbe/RpLB7kQnhfc\n2FNCsvvtTQTIvp9Oir829XNrZhp3WmwN9EvpOvCYW4EhsIYudV1bUQBdGPSpi2QZ\n0sXFBgNKnlUgN9OFRNztLalw\n-----END PRIVATE KEY-----\n"